# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'listener' do
  use_frameworks!
  pod 'Socket.IO-Client-Swift', '~> 15.2.0'

  target 'listenerTests' do
    inherit! :search_paths
  end

  target 'listenerUITests' do
  end

end
